# -*- coding: utf-8 -*-
"""
QO-100 Satellite Log Recording Software - Language Library
Supports multiple languages
"""

LANGUAGES = {
    "zh": {
        "title": "QO-100 日志记录软件 V1.0",
        "settings": "设置",
        "close": "关闭",
        "common_settings": "常用设置",
        "my_call": "我的呼号:",
        "my_grid": "我的网格(Grid):",
        "cq_zone": "CQ分区:",
        "itu_zone": "ITU分区:",
        "country_code": "国家:",
        "default_equipment": "默认设备:",
        "save": "保存",
        "cancel": "取消",
        "date_time": "日期和时间 (自动读取系统时间)",
        "utc_date": "UTC日期:",
        "utc_time": "UTC时间 (HH:MM:SS):",
        "date": "日期:",
        "time": "时间:",
        "info_input": "信息录入",
        "other_call": "对方呼号:",
        "down_freq": "下行频率 (MHz):",
        "up_freq": "上行频率 (MHz):",
        "my_rst": "我的RST:",
        "other_rst": "对方RST:",
        "mode": "模式:",
        "comment": "备注:",
        "export_adi": "导出ADI",
        "delete_last": "删除最后一条",
        "logs": "记录的日志",
        "no_logs": "还没有记录",
        "error": "错误",
        "warning": "警告",
        "success": "成功",
        "confirm": "确认",
        "input_my_call": "请先在设置中填写你的呼号",
        "input_other_call": "请填写对方呼号",
        "input_down_freq": "请填写下行频率",
        "freq_error": "频率输入有误",
        "no_logs_to_export": "没有日志可导出",
        "export_adi_success": "已导出ADI文件:",
        "export_failed": "导出失败:",
        "adi_file": "ADI文件",
        "all_files": "所有文件",
        "last_deleted": "已删除日志",
        "no_logs_to_delete": "没有日志可删除",
        "settings_saved": "设置已保存",
        "settings_open_error": "打开设置失败:",
        "delete_log": "删除",
        "edit_log": "编辑",
        "select_log_to_delete": "选择要删除的日志",
        "log_updated": "日志已更新",
        "edit_failed": "编辑失败",
        "confirm_delete_log": "确定要删除这条日志吗？",
    },
    "en": {
        "title": "QO-100 Logger V1.0",
        "settings": "Settings",
        "close": "Close",
        "common_settings": "Common Settings",
        "my_call": "My Callsign:",
        "my_grid": "My Grid:",
        "cq_zone": "CQ Zone:",
        "itu_zone": "ITU Zone:",
        "country_code": "Country Code:",
        "default_equipment": "Default Equipment:",
        "save": "Save",
        "cancel": "Cancel",
        "date_time": "Date and Time (Auto UTC)",
        "utc_date": "UTC Date:",
        "utc_time": "UTC Time (HH:MM:SS):",
        "date": "Date:",
        "time": "Time:",
        "info_input": "QSO Information",
        "other_call": "Other Callsign:",
        "down_freq": "RX Frequency (MHz):",
        "up_freq": "TX Frequency (MHz):",
        "my_rst": "My RST:",
        "other_rst": "Other RST:",
        "mode": "Mode:",
        "comment": "Comment:",
        "export_adi": "Export ADI",
        "delete_last": "Delete Last",
        "logs": "Recorded Logs",
        "no_logs": "No logs yet",
        "error": "Error",
        "warning": "Warning",
        "success": "Success",
        "confirm": "Confirm",
        "input_my_call": "Please set your callsign in settings first",
        "input_other_call": "Please enter other callsign",
        "input_down_freq": "Please enter RX frequency",
        "freq_error": "Frequency input error",
        "no_logs_to_export": "No logs to export",
        "export_adi_success": "ADI file exported:",
        "export_failed": "Export failed:",
        "adi_file": "ADI Files",
        "all_files": "All Files",
        "last_deleted": "Log deleted",
        "no_logs_to_delete": "No logs to delete",
        "settings_saved": "Settings saved",
        "settings_open_error": "Failed to open settings:",
        "delete_log": "Delete",
        "edit_log": "Edit",
        "select_log_to_delete": "Select log to delete",
        "log_updated": "Log updated",
        "edit_failed": "Edit failed",
        "confirm_delete_log": "Are you sure you want to delete this log?",
    },
    "es": {
        "title": "Registrador QO-100 V1.0",
        "settings": "Configuración",
        "close": "Cerrar",
        "common_settings": "Configuración Común",
        "my_call": "Mi Indicativo:",
        "my_grid": "Mi Cuadrícula:",
        "cq_zone": "Zona CQ:",
        "itu_zone": "Zona ITU:",
        "country_code": "Código de País:",
        "default_equipment": "Equipo Predeterminado:",
        "save": "Guardar",
        "cancel": "Cancelar",
        "date_time": "Fecha y Hora (UTC Auto)",
        "utc_date": "Fecha UTC:",
        "utc_time": "Hora UTC (HH:MM:SS):",
        "date": "Fecha:",
        "time": "Hora:",
        "info_input": "Información de QSO",
        "other_call": "Otro Indicativo:",
        "down_freq": "Frecuencia RX (MHz):",
        "up_freq": "Frecuencia TX (MHz):",
        "my_rst": "Mi RST:",
        "other_rst": "Otro RST:",
        "mode": "Modo:",
        "comment": "Comentario:",
        "export_adi": "Exportar ADI",
        "delete_last": "Eliminar Último",
        "logs": "Registros Grabados",
        "no_logs": "Sin registros aún",
        "error": "Error",
        "warning": "Advertencia",
        "success": "Éxito",
        "confirm": "Confirmar",
        "input_my_call": "Por favor, establezca su indicativo en configuración primero",
        "input_other_call": "Por favor, introduzca otro indicativo",
        "input_down_freq": "Por favor, introduzca la frecuencia RX",
        "freq_error": "Error de entrada de frecuencia",
        "no_logs_to_export": "Sin registros para exportar",
        "export_adi_success": "Archivo ADI exportado:",
        "export_failed": "Falló la exportación:",
        "adi_file": "Archivos ADI",
        "all_files": "Todos los Archivos",
        "last_deleted": "Registro eliminado",
        "no_logs_to_delete": "Sin registros para eliminar",
        "settings_saved": "Configuración guardada",
        "settings_open_error": "Error al abrir configuración:",
        "delete_log": "Eliminar",
        "edit_log": "Editar",
        "select_log_to_delete": "Seleccionar registro para eliminar",
        "log_updated": "Registro actualizado",
        "edit_failed": "Edición fallida",
        "confirm_delete_log": "¿Está seguro de que desea eliminar este registro?",
    },
    "de": {
        "title": "QO-100 Logger V1.0",
        "settings": "Einstellungen",
        "close": "Schließen",
        "common_settings": "Allgemeine Einstellungen",
        "my_call": "Mein Rufzeichen:",
        "my_grid": "Mein Gitter:",
        "cq_zone": "CQ-Zone:",
        "itu_zone": "ITU-Zone:",
        "country_code": "Ländercode:",
        "default_equipment": "Standardausrüstung:",
        "save": "Speichern",
        "cancel": "Abbrechen",
        "date_time": "Datum und Zeit (Auto UTC)",
        "utc_date": "UTC-Datum:",
        "utc_time": "UTC-Zeit (HH:MM:SS):",
        "date": "Datum:",
        "time": "Zeit:",
        "info_input": "QSO-Informationen",
        "other_call": "Anderes Rufzeichen:",
        "down_freq": "RX-Frequenz (MHz):",
        "up_freq": "TX-Frequenz (MHz):",
        "my_rst": "Mein RST:",
        "other_rst": "Anderes RST:",
        "mode": "Modus:",
        "comment": "Kommentar:",
        "export_adi": "ADI exportieren",
        "delete_last": "Letzte löschen",
        "logs": "Aufgezeichnete Protokolle",
        "no_logs": "Noch keine Protokolle",
        "error": "Fehler",
        "warning": "Warnung",
        "success": "Erfolg",
        "confirm": "Bestätigen",
        "input_my_call": "Bitte stellen Sie Ihr Rufzeichen zunächst in den Einstellungen ein",
        "input_other_call": "Bitte geben Sie ein anderes Rufzeichen ein",
        "input_down_freq": "Bitte geben Sie die RX-Frequenz ein",
        "freq_error": "Frequenzeingabefehler",
        "no_logs_to_export": "Keine Protokolle zum Exportieren",
        "export_adi_success": "ADI-Datei exportiert:",
        "export_failed": "Export fehlgeschlagen:",
        "adi_file": "ADI-Dateien",
        "all_files": "Alle Dateien",
        "last_deleted": "Protokoll gelöscht",
        "no_logs_to_delete": "Keine Protokolle zum Löschen",
        "settings_saved": "Einstellungen gespeichert",
        "settings_open_error": "Fehler beim Öffnen der Einstellungen:",
        "delete_log": "Löschen",
        "edit_log": "Bearbeiten",
        "select_log_to_delete": "Zu löschendes Protokoll auswählen",
        "log_updated": "Protokoll aktualisiert",
        "edit_failed": "Bearbeitung fehlgeschlagen",
        "confirm_delete_log": "Sind Sie sicher, dass Sie dieses Protokoll löschen möchten?",
    },
    "ja": {
        "title": "QO-100 ロガー V1.0",
        "settings": "設定",
        "close": "閉じる",
        "common_settings": "一般設定",
        "my_call": "私のコールサイン:",
        "my_grid": "私のグリッド:",
        "cq_zone": "CQゾーン:",
        "itu_zone": "ITUゾーン:",
        "country_code": "国コード:",
        "default_equipment": "デフォルト機器:",
        "save": "保存",
        "cancel": "キャンセル",
        "date_time": "日時（自動UTC）",
        "utc_date": "UTC日付:",
        "utc_time": "UTC時刻（HH:MM:SS）:",
        "date": "日付:",
        "time": "時刻:",
        "info_input": "QSO情報",
        "other_call": "相手のコールサイン:",
        "down_freq": "RX周波数（MHz）:",
        "up_freq": "TX周波数（MHz）:",
        "my_rst": "私のRST:",
        "other_rst": "相手のRST:",
        "mode": "モード:",
        "comment": "コメント:",
        "export_adi": "ADIをエクスポート",
        "delete_last": "最後を削除",
        "logs": "記録されたログ",
        "no_logs": "ログはまだありません",
        "error": "エラー",
        "warning": "警告",
        "success": "成功",
        "confirm": "確認",
        "input_my_call": "まず設定でコールサインを設定してください",
        "input_other_call": "相手のコールサインを入力してください",
        "input_down_freq": "RX周波数を入力してください",
        "freq_error": "周波数入力エラー",
        "no_logs_to_export": "エクスポートするログがありません",
        "export_adi_success": "ADIファイルがエクスポートされました:",
        "export_failed": "エクスポートに失敗しました:",
        "adi_file": "ADIファイル",
        "all_files": "すべてのファイル",
        "last_deleted": "ログが削除されました",
        "no_logs_to_delete": "削除するログがありません",
        "settings_saved": "設定が保存されました",
        "settings_open_error": "設定を開くことに失敗しました:",
        "delete_log": "削除",
        "edit_log": "編集",
        "select_log_to_delete": "削除するログを選択",
        "log_updated": "ログが更新されました",
        "edit_failed": "編集に失敗しました",
        "confirm_delete_log": "このログを削除してもよろしいですか？",
    },
    "fr": {
        "title": "Enregistreur QO-100 V1.0",
        "settings": "Paramètres",
        "close": "Fermer",
        "common_settings": "Paramètres Généraux",
        "my_call": "Mon Indicatif:",
        "my_grid": "Ma Grille:",
        "cq_zone": "Zone CQ:",
        "itu_zone": "Zone ITU:",
        "country_code": "Pays:",
        "default_equipment": "Équipement Défaut:",
        "save": "Enregistrer",
        "cancel": "Annuler",
        "date_time": "Date et Heure (UTC Auto)",
        "utc_date": "Date UTC:",
        "utc_time": "Heure UTC (HH:MM:SS):",
        "date": "Date:",
        "time": "Heure:",
        "info_input": "Informations QSO",
        "other_call": "Autre Indicatif:",
        "down_freq": "Fréquence RX (MHz):",
        "up_freq": "Fréquence TX (MHz):",
        "my_rst": "Mon RST:",
        "other_rst": "Autre RST:",
        "mode": "Mode:",
        "comment": "Commentaire:",
        "export_adi": "Exporter ADI",
        "delete_last": "Supprimer",
        "logs": "Journaux Enregistrés",
        "no_logs": "Pas de journaux",
        "error": "Erreur",
        "warning": "Avertissement",
        "success": "Succès",
        "confirm": "Confirmer",
        "input_my_call": "Veuillez d'abord définir votre indicatif dans les paramètres",
        "input_other_call": "Veuillez entrer un autre indicatif",
        "input_down_freq": "Veuillez entrer la fréquence RX",
        "freq_error": "Erreur de fréquence",
        "no_logs_to_export": "Aucun journal à exporter",
        "export_adi_success": "Fichier ADI exporté:",
        "export_failed": "Échec de l'export:",
        "adi_file": "Fichiers ADI",
        "all_files": "Tous les Fichiers",
        "last_deleted": "Journal supprimé",
        "no_logs_to_delete": "Aucun journal à supprimer",
        "settings_saved": "Paramètres enregistrés",
        "settings_open_error": "Impossible d'ouvrir les paramètres:",
        "delete_log": "Supprimer",
        "edit_log": "Modifier",
        "select_log_to_delete": "Sélectionner le journal à supprimer",
        "log_updated": "Journal mis à jour",
        "edit_failed": "Modification échouée",
        "confirm_delete_log": "Êtes-vous sûr de vouloir supprimer ce journal?",
    },
    "pt": {
        "title": "Registrador QO-100 V1.0",
        "settings": "Configurações",
        "close": "Fechar",
        "common_settings": "Configurações Gerais",
        "my_call": "Meu Indicativo:",
        "my_grid": "Minha Grade:",
        "cq_zone": "Zona CQ:",
        "itu_zone": "Zona ITU:",
        "country_code": "País:",
        "default_equipment": "Equipamento Padrão:",
        "save": "Salvar",
        "cancel": "Cancelar",
        "date_time": "Data e Hora (UTC Auto)",
        "utc_date": "Data UTC:",
        "utc_time": "Hora UTC (HH:MM:SS):",
        "date": "Data:",
        "time": "Hora:",
        "info_input": "Informações de QSO",
        "other_call": "Outro Indicativo:",
        "down_freq": "Frequência RX (MHz):",
        "up_freq": "Frequência TX (MHz):",
        "my_rst": "Meu RST:",
        "other_rst": "Outro RST:",
        "mode": "Modo:",
        "comment": "Comentário:",
        "export_adi": "Exportar ADI",
        "delete_last": "Excluir",
        "logs": "Registros Gravados",
        "no_logs": "Sem registros",
        "error": "Erro",
        "warning": "Aviso",
        "success": "Sucesso",
        "confirm": "Confirmar",
        "input_my_call": "Primeiro, defina seu indicativo nas configurações",
        "input_other_call": "Digite outro indicativo",
        "input_down_freq": "Digite a frequência RX",
        "freq_error": "Erro de frequência",
        "no_logs_to_export": "Nenhum registro para exportar",
        "export_adi_success": "Arquivo ADI exportado:",
        "export_failed": "Falha na exportação:",
        "adi_file": "Arquivos ADI",
        "all_files": "Todos os Arquivos",
        "last_deleted": "Registro excluído",
        "no_logs_to_delete": "Nenhum registro para excluir",
        "settings_saved": "Configurações salvas",
        "settings_open_error": "Falha ao abrir configurações:",
        "delete_log": "Excluir",
        "edit_log": "Editar",
        "select_log_to_delete": "Selecione o registro para excluir",
        "log_updated": "Registro atualizado",
        "edit_failed": "Falha na edição",
        "confirm_delete_log": "Tem certeza de que deseja excluir este registro?",
    },
    "el": {
        "title": "Καταγραφέας QO-100 V1.0",
        "settings": "Ρυθμίσεις",
        "close": "Κλείσιμο",
        "common_settings": "Γενικές Ρυθμίσεις",
        "my_call": "Το Σήμα Μου:",
        "my_grid": "Το Πλέγμα Μου:",
        "cq_zone": "Ζώνη CQ:",
        "itu_zone": "Ζώνη ITU:",
        "country_code": "Χώρα:",
        "default_equipment": "Προεπιλεγμένος Εξοπλισμός:",
        "save": "Αποθήκευση",
        "cancel": "Ακύρωση",
        "date_time": "Ημερομηνία και Ώρα (UTC Auto)",
        "utc_date": "Ημερομηνία UTC:",
        "utc_time": "Ώρα UTC (HH:MM:SS):",
        "date": "Ημερομηνία:",
        "time": "Ώρα:",
        "info_input": "Πληροφορίες QSO",
        "other_call": "Άλλο Σήμα:",
        "down_freq": "Συχνότητα RX (MHz):",
        "up_freq": "Συχνότητα TX (MHz):",
        "my_rst": "Το RST Μου:",
        "other_rst": "Άλλο RST:",
        "mode": "Τρόπος:",
        "comment": "Σχόλιο:",
        "export_adi": "Εξαγωγή ADI",
        "delete_last": "Διαγραφή",
        "logs": "Καταγραμμένα Αρχεία Καταγραφής",
        "no_logs": "Δεν υπάρχουν αρχεία",
        "error": "Σφάλμα",
        "warning": "Προειδοποίηση",
        "success": "Επιτυχία",
        "confirm": "Επιβεβαίωση",
        "input_my_call": "Παρακαλώ ορίστε πρώτα το σήμα σας στις ρυθμίσεις",
        "input_other_call": "Παρακαλώ εισαγάγετε άλλο σήμα",
        "input_down_freq": "Παρακαλώ εισαγάγετε τη συχνότητα RX",
        "freq_error": "Σφάλμα συχνότητας",
        "no_logs_to_export": "Κανένα αρχείο για εξαγωγή",
        "export_adi_success": "Αρχείο ADI εξήχθη:",
        "export_failed": "Αποτυχία εξαγωγής:",
        "adi_file": "Αρχεία ADI",
        "all_files": "Όλα τα Αρχεία",
        "last_deleted": "Αρχείο διαγράφηκε",
        "no_logs_to_delete": "Κανένα αρχείο για διαγραφή",
        "settings_saved": "Ρυθμίσεις αποθηκεύτηκαν",
        "settings_open_error": "Αποτυχία ανοίγματος ρυθμίσεων:",
        "delete_log": "Διαγραφή",
        "edit_log": "Επεξεργασία",
        "select_log_to_delete": "Επιλέξτε αρχείο για διαγραφή",
        "log_updated": "Αρχείο ενημερώθηκε",
        "edit_failed": "Επεξεργασία απέτυχε",
        "confirm_delete_log": "Είστε σίγουρος ότι θέλετε να διαγράψετε αυτό το αρχείο;",
    },
    "ar": {
        "title": "مسجل QO-100 V1.0",
        "settings": "الإعدادات",
        "close": "إغلاق",
        "common_settings": "الإعدادات العامة",
        "my_call": "مؤشري:",
        "my_grid": "شبكتي:",
        "cq_zone": "منطقة CQ:",
        "itu_zone": "منطقة ITU:",
        "country_code": "الدولة:",
        "default_equipment": "المعدات الافتراضية:",
        "save": "حفظ",
        "cancel": "إلغاء",
        "date_time": "التاريخ والوقت (UTC تلقائي)",
        "utc_date": "تاريخ UTC:",
        "utc_time": "الوقت UTC (HH:MM:SS):",
        "date": "التاريخ:",
        "time": "الوقت:",
        "info_input": "معلومات QSO",
        "other_call": "المؤشر الآخر:",
        "down_freq": "تردد RX (MHz):",
        "up_freq": "تردد TX (MHz):",
        "my_rst": "RST الخاص بي:",
        "other_rst": "RST الآخر:",
        "mode": "الوضع:",
        "comment": "التعليق:",
        "export_adi": "تصدير ADI",
        "delete_last": "حذف",
        "logs": "السجلات المسجلة",
        "no_logs": "لا توجد سجلات",
        "error": "خطأ",
        "warning": "تحذير",
        "success": "نجح",
        "confirm": "تأكيد",
        "input_my_call": "يرجى تعيين المؤشر الخاص بك أولاً في الإعدادات",
        "input_other_call": "يرجى إدخال مؤشر آخر",
        "input_down_freq": "يرجى إدخال تردد RX",
        "freq_error": "خطأ في التردد",
        "no_logs_to_export": "لا توجد سجلات للتصدير",
        "export_adi_success": "تم تصدير ملف ADI:",
        "export_failed": "فشل التصدير:",
        "adi_file": "ملفات ADI",
        "all_files": "جميع الملفات",
        "last_deleted": "تم حذف السجل",
        "no_logs_to_delete": "لا توجد سجلات للحذف",
        "settings_saved": "تم حفظ الإعدادات",
        "settings_open_error": "فشل في فتح الإعدادات:",
        "delete_log": "حذف",
        "edit_log": "تعديل",
        "select_log_to_delete": "اختر السجل للحذف",
        "log_updated": "تم تحديث السجل",
        "edit_failed": "فشل التعديل",
        "confirm_delete_log": "هل أنت متأكد من رغبتك في حذف هذا السجل؟",
    }
}

def get_language(lang_code="zh"):
    """Get the text library for the specified language"""
    return LANGUAGES.get(lang_code, LANGUAGES["en"])

def get_available_languages():
    """Get the list of available languages"""
    return list(LANGUAGES.keys())

def get_language_names():
    """Get language name mapping"""
    return {
        "zh": "中文 (Chinese)",
        "en": "English",
        "es": "Español (Spanish)",
        "de": "Deutsch (German)",
        "ja": "日本語 (Japanese)",
        "fr": "Français (French)",
        "pt": "Português (Portuguese)",
        "el": "Ελληνικά (Greek)",
        "ar": "العربية (Arabic)"
    }
